build: false

environment:
  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"



init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"


test_script:
  - "cd source"
  - "%PYTHON%/python.exe setup.py test"